apiVersion: v1
kind: Pod
metadata:
  name: springbootapp
  labels:
    role: webapp
spec:
  containers:
    - name: web
      image: pradeepcd/springboot-app:1.0
      ports:
        - containerPort: 80
          name: web
          protocol: TCP